export { default as About } from './about/About'
export { default as Contact } from './contact/Contact'
export { default as Features } from './features/Features'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Navbar } from './navbar/Navbar'
export { default as Story } from './story/Story'